language: cpp
before_install:
  - wget https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz
  - tar xzf cmake-3.9.4-Linux-x86_64.tar.gz
  - wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz
  - tar xzf SFML-2.4.2-linux-gcc-64-bit.tar.gz
script:
  - ./cmake-3.9.4-Linux-x86_64/bin/cmake . -DSFML_INCLUDE_DIR=/SFML-2.4.2-linux-gcc-64-bit/include && make
